export const ADD_FRIEND = 'ADD_FRIEND'
export const STAR_FRIEND = 'STAR_FRIEND'
export const DELETE_FRIEND = 'DELETE_FRIEND'

export const CHOOSE_MONSTER = 'CHOOSE_MONSTER'

export const CHOOSE_MOVE = 'CHOOSE_MOVE'
export const RESET_MOVE = 'RESET_MOVE'
export const CHANGE_MONSTER = 'CHANGE_MONSTER'
export const RESET_MONSTER_MAKER = 'RESET_MONSTER_MAKER'
